### ISSUE TITLE
Driver does not build on Ubuntu 18.04

### ISSUE THREAD

**Issue by vittorio88** [vittorio88/WAVE300#7]
When attempting to build driver on Ubuntu 18.04, the following error is seen:
error: conflicting types for 'copy_file_range()' 

This identifier collision was introduced by glibc 2.2.7 used in Ubuntu 18.04.

**Comment by ahmar20** [comment]
I am having another issue. I am running Ubuntu 18.04 but the issue is rather different than yours above.
`ahmar@Ahmar-Laptop:~/src/WAVE300$ make menuconfig
make: *** No rule to make target 'menuconfig'.  Stop.`

I have already done the export command as you detailed in the README file. But `make` or `make menuconfig` doesnt work. Any pointers?

**Comment by ahmar20** [comment]
Does that mean there are more than one types of the above function? If that is the case then maybe there is a way to detect what version we are running and then choose the appropriate function accordingly.

**Comment by ahmar20** [comment]
I builr for LEDE 17.01 branch but I'll be building for 18.06.1 also just to make sure whether it works or not. Then I'll report back.

**Comment by ahmar20** [comment]
I was able to build the driver for Openwrt 18.06.1 on Ubuntu 18.04 without any errors. I am using WSL so maybe the error occurs for some other reason that is not related to build process maybe.

**Comment by vittorio88** [comment]
I recently tested building on 18.04.04 Ubuntu native, and it works fine. Closing.
